version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - dbdata:/var/lib/postgresql/data

  go:
    container_name: test-task
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "minio"
      - "postgres"
    environment:
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}

  migrate:
    image: migrate/migrate:latest
    container_name: migrate
    depends_on:
      - "postgres"
    volumes:
      - ./schema:/schema
    command:
      [
        "-path",
        "/schema",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}",
        "up",
      ]
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

volumes:
  dbdata:
  minio_storage:
